name: auto_reconnect_websocket
description: Provides a WebSocketChannel that can reconnect
version: 0.0.1
homepage: https://github.com/XuanTung95/auto_reconnect_websocket.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  web_socket_channel: ^2.2.0
